workflows:
  android-build:
    name: Build Android APK
    instance_type: mac_mini_m1
    max_build_duration: 30
    scripts:
      - name: Set permissions
        script: chmod +x gradlew
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
